<?php


/**
 * @file
 * Provides a customized weather report using open weather API.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function leo_weather_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.leo_weather':
            $output = file_get_contents(drupal_get_path('module', 'leo_weather') . '/README.txt');
            return $output;
    }
}

/**
 * Implements hook_theme().
 */
function leo_weather_theme($existing, $type, $theme, $path) {
  return [
    'leo_weather' => [
        'variables' => ['leo_weather_detail' => NULL],
    ],
  ];
}
